/* eslint-disable @typescript-eslint/no-unused-vars */
import { ragChat } from "@/lib/rag-chat";
import { aiUseChatAdapter } from "@upstash/rag-chat/nextjs";
import { NextRequest, NextResponse } from "next/server";

export const POST = async (req: NextRequest, res: NextResponse) => {
  try {
    const { messages, sessionId } = await req.json()

    const lastMessage = messages[messages.length - 1].content // I'm assuming the last message is the one that the user wants to send

    const response = await ragChat.chat(lastMessage, { streaming: true, sessionId })
    //console.log("response", response)
    return aiUseChatAdapter(response) // The message is generated by the AI
  } catch (error) {
    console.error(error as unknown)
    return NextResponse.json({ error: error }, { status: 500 })
  }
}